name: Java CI with Maven

env:
  NAME: 'Snyk Demo'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      JAVA_VERSION: '21'
    runs-on: ubuntu-latest

    steps:
# Disabling the real work because I only want to see how secrets work
#    - uses: actions/checkout@v3
#    - name: Set up JDK ${{env.JAVA_VERSION}}
#      uses: actions/setup-java@v3
#      with:
#        java-version: ${{env.JAVA_VERSION}}
#        distribution: 'temurin'
#        cache: maven
#    - name: Build with Maven
#      run: mvn -B package --file pom.xml
    - name: Print name
      run: echo "Hello $NAME. $BUILD. Using Java Version $JAVA_VERSION. My API_KEY is ${{secrets.API_KEY}}"
      env:
        BUILD: 'We are currently running the Build job'
    - name: Print only secret
      run: echo "${{secrets.API_KEY}}"

